Script started on Tue 12 Aug 2014 02:12:39 PM PDT
]0;william@william-Inspiron-N5110: ~/cs100/hw12/rshell/testswilliam@william-Inspiron-N5110:~/cs100/hw12/rshell/tests$ cd ..
]0;william@william-Inspiron-N5110: ~/cs100/hw12/rshellwilliam@william-Inspiron-N5110:~/cs100/hw12/rshell$ make
g++ -Wall -Werror -ansi -pedantic src/main.cpp -o ./bin/rshell
g++ -Wall -Werror -ansi -pedantic src/ls.cpp -o ./bin/ls
]0;william@william-Inspiron-N5110: ~/cs100/hw12/rshellwilliam@william-Inspiron-N5110:~/cs100/hw12/rshell$ bin/ls
README.md bin src LICENSE tests Makefile 
]0;william@william-Inspiron-N5110: ~/cs100/hw12/rshellwilliam@william-Inspiron-N5110:~/cs100/hw12/rshell$ bin/ls -a
README.md . .. bin src LICENSE tests .git Makefile 
]0;william@william-Inspiron-N5110: ~/cs100/hw12/rshellwilliam@william-Inspiron-N5110:~/cs100/hw12/rshell$ bin/ls -a[Kl
-rw- README.md
drwx bin
drwx src
-rw- LICENSE
drwx tests
-rw- Makefile

]0;william@william-Inspiron-N5110: ~/cs100/hw12/rshellwilliam@william-Inspiron-N5110:~/cs100/hw12/rshell$ [K]0;william@william-Inspiron-N5110: ~/cs100/hw12/rshellwilliam@william-Inspiron-N5110:~/cs100/hw12/rshell$ bin/ls -l
-rw-rw-r-- README.md
drwxrwxr-x bin
drwxrwxr-x src
-rw-rw-r-- LICENSE
drwxrwxr-x tests
-rw-rw-r-- Makefile

]0;william@william-Inspiron-N5110: ~/cs100/hw12/rshellwilliam@william-Inspiron-N5110:~/cs100/hw12/rshell$ ls
[0m[01;34mbin[0m  LICENSE  Makefile  README.md  [01;34msrc[0m  [01;34mtests[0m
]0;william@william-Inspiron-N5110: ~/cs100/hw12/rshellwilliam@william-Inspiron-N5110:~/cs100/hw12/rshell$ exit
exit

Script done on Tue 12 Aug 2014 02:21:25 PM PDT
